// This file will be automatically generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id your-project-id > lib/supabase/database.types.ts

export type Database = {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string
          title: string
          slug: string
          logo_url: string | null
          live_url: string | null
          description: string | null
          testimonial: string | null
          testimonial_author: string | null
          test_url: string | null
          status_id: string | null
          version: string | null
          latest_milestone: string | null
          best_metric: string | null
          contact_email: string | null
          created_at: string
          updated_at: string
          is_published: boolean
          published_at: string | null
        }
        Insert: {
          id?: string
          title: string
          slug: string
          logo_url?: string | null
          live_url?: string | null
          description?: string | null
          testimonial?: string | null
          testimonial_author?: string | null
          test_url?: string | null
          status_id?: string | null
          version?: string | null
          latest_milestone?: string | null
          best_metric?: string | null
          contact_email?: string | null
          created_at?: string
          updated_at?: string
          is_published?: boolean
          published_at?: string | null
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          logo_url?: string | null
          live_url?: string | null
          description?: string | null
          testimonial?: string | null
          testimonial_author?: string | null
          test_url?: string | null
          status_id?: string | null
          version?: string | null
          latest_milestone?: string | null
          best_metric?: string | null
          contact_email?: string | null
          created_at?: string
          updated_at?: string
          is_published?: boolean
          published_at?: string | null
        }
      }
      // Add other table types as needed
    }
  }
}